<?php
/**
 * Plugin Name: NH3 Mag - Blocks
 * Description: Add a new set of NH3 related Gutenberg blocks
 * Version:     2.3.10
 * Author:      Media Engineering Institute (MEI)
 * Author URI:  https://heig-vd.ch/rad/instituts/mei/
 * Text Domain: nh3-mag-blocks
 * Domain Path: /languages
 */

// THIS FILE IS AUTOMATICALLY GENERATED !
// DO NOT ALTER ITS CONTENT

// Main plugin file path
define( 'NH3_BLOCKS_MAIN_FILE', __FILE__ );

// Bootstrap the plugin.
require_once 'bootstrap.php';
