<?php
/**
 * Plugin Name: NH3 Mag - Archive Image Block
 * Description: Add a Gutenberg block for embedding images from the NH3 archive
 * Version:     0.0.1
 * Author:      MEI
 * Author URI:  https://heig-vd.ch/rad/instituts/mei/
 * Text Domain: nh3-mag-archive-photo
 * Domain Path: /languages
 */

// THIS FILE IS AUTOMATICALLY GENERATED !
// DO NOT ALTER ITS CONTENT

// Main plugin file path
define('NH3_MAG_ARCHIVE_IMAGE_BLOCK_MAIN_FILE', __FILE__);

// Bootstrap the plugin.
require_once 'bootstrap.php';
