<?php
/**
 * Plugin Name: NH3 Mag - Archive Blocks
 * Description: Add Gutenberg blocks for embedding NH3 documents in a post
 * Version:     0.0.2
 * Author:      MEI
 * Author URI:  https://heig-vd.ch/rad/instituts/mei/
 * Text Domain: nh3-mag-archive-blocks
 * Domain Path: /languages
 */

// THIS FILE IS AUTOMATICALLY GENERATED !
// DO NOT ALTER ITS CONTENT

// Main plugin file path
define('NH3_MAG_ARCHIVE_BLOCKS_MAIN_FILE', __FILE__);

// Bootstrap the plugin.
require_once 'bootstrap.php';
